# end_points data

In [2]:
from scannet_val import ScannetValDataset

test_dataset = ScannetValDataset(all_classes=True,
                                    num_novel_class=9,
                                    num_points=40000,
                                    augment=False)

data = test_dataset[46]
print(data.keys())

VALIDATION_DATA_PATH: /home/peisheng/SDCoT/scannet/scannet_val_detection_data
Testing classes: ['bathtub', 'bed', 'bookshelf', 'cabinet', 'chair', 'counter', 'curtain', 'desk', 'door', 'otherfurniture', 'picture', 'refrigerator', 'showercurtain', 'sink', 'sofa', 'table', 'toilet', 'window'] | number of scenes: 312
dict_keys(['point_clouds', 'center_label', 'heading_class_label', 'heading_residual_label', 'size_residual_label', 'sem_cls_label', 'box_label_mask', 'vote_label', 'vote_label_mask'])


In [3]:
center_label = data["center_label"]
heading_class_label = data["heading_class_label"]
heading_residual_label = data["heading_residual_label"]
size_residual_label = data["size_residual_label"]
sem_cls_label = data["sem_cls_label"]

print(len(center_label))

print("-------------------------- Center Label --------------------------")
print(center_label)
print("-------------------------- Heading Class Label --------------------------")
print(heading_class_label)
print("-------------------------- Heading Residual Label --------------------------")
print(heading_residual_label)
print("-------------------------- Size Residual Label --------------------------")
print(size_residual_label)
print("-------------------------- Semantic Class Label --------------------------")
print(sem_cls_label)

64
-------------------------- Center Label --------------------------
[[-0.7182697   1.2471408   0.6583613 ]
 [ 0.6342453   0.82686526  0.49707964]
 [ 0.71425563 -0.31277555  0.6422175 ]
 [-0.10494043 -1.6142914   0.90692395]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.    

In [4]:
center_label = data["center_label"]
heading_class_label = data["heading_class_label"]
heading_residual_label = data["heading_residual_label"]
size_residual_label = data["size_residual_label"]
sem_cls_label = data["sem_cls_label"]

print(len(center_label))

print("-------------------------- Center Label --------------------------")
print(center_label[0])
print("-------------------------- Heading Class Label --------------------------")
print(heading_class_label[0])
print("-------------------------- Heading Residual Label --------------------------")
print(heading_residual_label[0])
print("-------------------------- Size Residual Label --------------------------")
print(size_residual_label[0])
print("-------------------------- Semantic Class Label --------------------------")
print(sem_cls_label[0])

64
-------------------------- Center Label --------------------------
[-0.7182697  1.2471408  0.6583613]
-------------------------- Heading Class Label --------------------------
0
-------------------------- Heading Residual Label --------------------------
0.0
-------------------------- Size Residual Label --------------------------
[-0.05631945 -0.1493014   0.6465251 ]
-------------------------- Semantic Class Label --------------------------
9


In [5]:
import numpy as np
import matplotlib.pyplot as plt
from scannet_val import ScannetValDataset
import open3d as o3d
import os

classes = ['bathtub', 'bed', 'bookshelf', 'cabinet', 'chair', 'counter', 'curtain', 'desk', 'door', 'otherfurniture',
                      'picture', 'refrigerator', 'showercurtain', 'sink', 'sofa', 'table', 'toilet', 'window']

box_sizes = {'cabinet': np.array([0.76966726, 0.81160211, 0.92573741]),
                       'bed': np.array([1.876858, 1.84255952, 1.19315654]),
                       'chair': np.array([0.61327999, 0.61486087, 0.71827014]),
                       'sofa': np.array([1.39550063, 1.51215451, 0.83443565]),
                       'table': np.array([0.97949596, 1.06751485, 0.63296875]),
                       'door': np.array([0.53166301, 0.59555772, 1.75001483]),
                       'window': np.array([0.96247056, 0.72462326, 1.14818682]),
                       'bookshelf': np.array([0.83221924, 1.04909355, 1.68756634]),
                       'picture': np.array([0.21132214, 0.4206159 , 0.53728459]),
                       'counter': np.array([1.44400728, 1.89708334, 0.26985747]),
                       'desk': np.array([1.02942616, 1.40407966, 0.87554322]),
                       'curtain': np.array([1.37664116, 0.65521793, 1.68131292]),
                       'refrigerator': np.array([0.66508189, 0.71111926, 1.29885307]),
                       'showercurtain': np.array([0.41999174, 0.37906947, 1.75139715]),
                       'toilet': np.array([0.59359559, 0.59124924, 0.73919014]),
                       'sink': np.array([0.50867595, 0.50656087, 0.30136236]),
                       'bathtub': np.array([1.15115265, 1.0546296 , 0.49706794]),
                       'otherfurniture': np.array([0.47535286, 0.49249493, 0.58021168])
                        }

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [6]:
center = center_label[0]
heading = heading_class_label[0] * (2 * np.pi / 12) + heading_residual_label[0]
classname = classes[sem_cls_label[0]]
size = box_sizes[classname] + size_residual_label[0]

print(center)
print(heading)
print(classname)
print(size)

[-0.7182697  1.2471408  0.6583613]
0.0
otherfurniture
[0.41903341 0.34319354 1.22673676]


## 3d box corners data

In [7]:
filepath = "../val_bboxes/scene0146_00_gt.npy"
gt = np.load(filepath, allow_pickle=True)
#print(gt)
print(gt[0]['bbox'].shape)
print(gt[0]['bbox'])

(8, 3)
[[-0.508753   -0.04499293  1.41873753]
 [-0.508753   -0.04499293  1.075544  ]
 [-0.92778641 -0.04499293  1.075544  ]
 [-0.92778641 -0.04499293  1.41873753]
 [-0.508753   -1.2717297   1.41873753]
 [-0.508753   -1.2717297   1.075544  ]
 [-0.92778641 -1.2717297   1.075544  ]
 [-0.92778641 -1.2717297   1.41873753]]


In [30]:
def roty(t):
    """Rotation about the y-axis."""
    c = np.cos(t)
    s = np.sin(t)
    return np.array([[c,  0,  s],
                    [0,  1,  0],
                    [-s, 0,  c]])

def inverse_get_3d_box(corners_3d):
    # Transpose to get (3, 8) shape
    corners_3d = corners_3d.T
    print("corners_3d shape:", corners_3d.shape)

    # Recover the center by calculating the mean of the corners
    center = np.mean(corners_3d, axis=1)
    print("center shape:", center.shape)

    # Translate corners back to origin
    corners_3d[0, :] -= center[0]
    corners_3d[1, :] -= center[1]
    corners_3d[2, :] -= center[2]

    # Determine the heading angle by examining the direction of the corners
    x_corners = corners_3d[0, :]
    z_corners = corners_3d[2, :]
    heading_angle = np.arctan2(z_corners[1] - z_corners[0], x_corners[1] - x_corners[0])

    # Rotate corners back to axis-aligned state
    R = roty(-heading_angle)
    aligned_corners = np.dot(R, corners_3d)

    # Determine the box size from the extents of the aligned corners
    l = np.max(aligned_corners[0, :]) - np.min(aligned_corners[0, :])
    w = np.max(aligned_corners[2, :]) - np.min(aligned_corners[2, :])
    h = np.max(aligned_corners[1, :]) - np.min(aligned_corners[1, :])
    
    # modifications:
    box_size = [w, l, h]

    heading_angle = 0
    
    new_center = center.copy()
    new_center[1] = center[2]
    new_center[2] = -center[1]
    
    return box_size, heading_angle, new_center

In [9]:
box_size, heading_angle, center = inverse_get_3d_box(gt[0]['bbox'])

print("Box size:", box_size)
print("Heading angle:", heading_angle)
print("Center:", center)

corners_3d shape: (3, 8)
center shape: (3,)
Box size: [0.34319353517978657, 0.4190334071777917, 1.2267367649723817]
Heading angle: -1.5707963267948966
Center: [-0.71826971 -0.65836132  1.24714077]


Center: [-0.7182697  1.2471408  0.6583613]

Heading: 0.0

otherfurniture

Size: [0.41903341 0.34319354 1.22673676]

In [31]:
from scannet_val import ScannetValDataset

def test_inverse_get_3d_box(img_id):
    
    test_dataset = ScannetValDataset(all_classes=True,
                                    num_novel_class=9,
                                    num_points=40000,
                                    augment=False)
    
    data = test_dataset[img_id] # same as end_points
    
    center_label = data["center_label"]
    heading_class_label = data["heading_class_label"]
    heading_residual_label = data["heading_residual_label"]
    size_residual_label = data["size_residual_label"]
    sem_cls_label = data["sem_cls_label"]
    
    scanname = test_dataset.scan_names[img_id]

    filepath = f"../val_bboxes/{scanname}_gt.npy"
    gt = np.load(filepath, allow_pickle=True)
    
    no_bbox = len(gt)
    print("Number of Bounding Boxes:", no_bbox)
    
    for i in range(no_bbox):
        center = center_label[i]
        heading = heading_class_label[i] * (2 * np.pi / 12) + heading_residual_label[i]
        classname = classes[sem_cls_label[i]]
        size = box_sizes[classname] + size_residual_label[i]

        print("Original box size:", size)
        print("Original heading: ",heading)
        print("Original center: ", center)

        box_size, heading_angle, center = inverse_get_3d_box(gt[i]['bbox'])

        print("Inversed Box size:", box_size)
        print("Inversed Heading angle:", heading_angle)
        print("Inversed Center:", center)
        
        print("-----------------------------------------------------------------------------")

In [32]:
test_inverse_get_3d_box(46)

VALIDATION_DATA_PATH: /home/peisheng/SDCoT/scannet/scannet_val_detection_data
Testing classes: ['bathtub', 'bed', 'bookshelf', 'cabinet', 'chair', 'counter', 'curtain', 'desk', 'door', 'otherfurniture', 'picture', 'refrigerator', 'showercurtain', 'sink', 'sofa', 'table', 'toilet', 'window'] | number of scenes: 312
Number of Bounding Boxes: 4
Original box size: [0.41903341 0.34319354 1.22673676]
Original heading:  0.0
Original center:  [-0.7182697  1.2471408  0.6583613]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [0.4190334071777917, 0.34319353517978657, 1.2267367649723817]
Inversed Heading angle: 0
Inversed Center: [-0.71826971  1.24714077  0.65836132]
-----------------------------------------------------------------------------
Original box size: [0.62731349 0.38432801 0.86561101]
Original heading:  0.0
Original center:  [0.6342453  0.82686526 0.49707964]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [0.627313494239893, 0.38432800527309413, 0.865611

In [25]:
test_inverse_get_3d_box(1)

VALIDATION_DATA_PATH: /home/peisheng/SDCoT/scannet/scannet_val_detection_data
Testing classes: ['bathtub', 'bed', 'bookshelf', 'cabinet', 'chair', 'counter', 'curtain', 'desk', 'door', 'otherfurniture', 'picture', 'refrigerator', 'showercurtain', 'sink', 'sofa', 'table', 'toilet', 'window'] | number of scenes: 312
Number of Bounding Boxes: 23
Original box size: [0.25318372 1.08383798 1.91491351]
Original heading:  0.0
Original center:  [ 1.3510225 -2.7796478  0.843703 ]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [1.0838379816281893, 0.2531837240587614, 1.914913505771942]
Inversed Heading angle: -1.5707963267948966
Inversed Center: [ 1.35102248 -0.84370297 -2.77964783]
-----------------------------------------------------------------------------
Original box size: [0.52975696 0.60041463 1.04436372]
Original heading:  0.0
Original center:  [-1.0569172  -0.37489235  0.5795717 ]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [0.976333136962662, 0.1806422

In [26]:
test_inverse_get_3d_box(2)

VALIDATION_DATA_PATH: /home/peisheng/SDCoT/scannet/scannet_val_detection_data
Testing classes: ['bathtub', 'bed', 'bookshelf', 'cabinet', 'chair', 'counter', 'curtain', 'desk', 'door', 'otherfurniture', 'picture', 'refrigerator', 'showercurtain', 'sink', 'sofa', 'table', 'toilet', 'window'] | number of scenes: 312
Number of Bounding Boxes: 31
Original box size: [0.45735527 0.30726767 0.41326358]
Original heading:  0.0
Original center:  [ 1.3547319 -2.0514004  0.5902159]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [0.3072676733695224, 0.4573552674477006, 0.41326357633651734]
Inversed Heading angle: -1.5707963267948966
Inversed Center: [ 1.35473192 -0.59021592 -2.05140042]
-----------------------------------------------------------------------------
Original box size: [0.4431218  0.23577834 0.25663792]
Original heading:  0.0
Original center:  [ 1.975533  -2.1745129  0.6898607]
corners_3d shape: (3, 8)
center shape: (3,)
Inversed Box size: [0.23577833926307704, 0.443121

Box size should be: 1, 0, 2

Heading should be just 0

Center should be: 0, 2, -1